### ISSUE TITLE
Add option on refresh to skip module download

### ISSUE THREAD

**Issue by TonyGravagno** [grakkit/core#2]
It would be helpful if a web request was not done on every manual refresh operation. This is very fast when there are no modules. In development mode, when there are modules, I think this will become a small burden. For now, I commented out these lines in index.js:
```js
console.log('Downloading official module list...');
trusted = core.fetch(`${master}/modules.json`).json();
```
Please consider adding another argument after "refresh" a flag in a config file in the file system, or even just a Boolean flag at the top of index.js. Thanks.

**Comment by hb432** [comment]
I will add `/grakkit toggle <feature>` with `<feature>` being `"user"`, `"scripts"`, `"trusted"`, or `"dict"`
