### ISSUE TITLE
Prevent update from deleting assets

### ISSUE THREAD

**Issue by TonyGravagno** [grakkit/core#3]
Ref https://github.com/grakkit/core/issues/2#issuecomment-691552044

The new `/grakkit toggle` allows us to toggle which assets are updated. But when dict updates are toggled off, the existing dict folder is deleted. Please change this to simply avoid the update of an existing folder, without deleting the folder.

Please also apply this to modules if required.

Reason:  A developer might want to make changes to local assets, and then disable updates to avoid having the changes over-written. The current update will delete those changes.

If there is anywhere else where developer assets might be deleted, please change how it works. I don't know if more toggles would help like "dict" disables the update while p_dict disables the update and preserves the existing assets.

Thanks

**Comment by hb432** [comment]
Fixed!
